codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
      only_pulls: false
        branches: null
        flags: null
    paths: null

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
