language: java
sudo: false
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script:
  - ./gradlew clean build
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: opensourcekr:3wXZfw1QFGKrbPrNR99ZLR10