spring:
  profiles:
    active: dev


---
spring:
  profiles: dev
  # 시작할때 실행시킬 script
  datasource:
    url: jdbc:h2:mem:snack
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

---
spring:
  profiles: release

  datasource:
    data:
      url: jdbc:mysql://localhost:3306/news?serverTimezone=UTC
      username: root
      password:

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create