name: SNAK-CI

on:
  push:
    branches:
      - master
      - develop
      - 'feature/*'
  pull_request:
    branches:
      - '*'

jobs:
  linux:
    name: 'Linux'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'Set up Java 8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: 'Gradle Version'
        run:  ./gradlew --version
      - name: 'Build with Gradle'
        run: ./gradlew build
      - name: 'Slack Notification'
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEB_HOOK }}
          SLACK_USERNAME: Snak-CI
          SLACK_ICON: https://snak.news/aa63c82b3da4ad0111684fc1a93fabdb.png
          SLACK_COLOR: '#3278BD'
          SLACK_TITLE: Snak-Build-Status
          SLACK_MESSAGE: 'Build Success :rocket:'

  coverage:
    name: 'Coverage'
    needs: linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'Set up Java 8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: 'Run tests with JaCoCo'
        shell: bash
        run: |
          ./gradlew --version
          ./gradlew build jacocoTestReport
      - name: 'Upload to Codecov.io'
        shell: bash
        run: |
          bash <(curl -s https://codecov.io/bash)